### ISSUE TITLE
10k Potentiometer missing from BOM

### ISSUE THREAD

**Issue by 4n0m4l0u5** [DIY-Machines/Kinetic-Sand-Art-Table#1]
First let me thank you for putting in the effort to post this project! Could you please add a link to the nice looking pots you used?

**Comment by DIY-Machines** [comment]
Hi, I'm glad you like the project. I've added in the link to the 10k pots, thanks for letting me know.
Here is the link for convenience: 10k potentiometers (x2) : https://geni.us/Potentiometers
